# Generated by Django 5.1.3 on 2024-11-27 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age_group', models.CharField(choices=[('18-25', '18-25'), ('26-40', '26-40'), ('41-60', '41-60'), ('60+', '60+')], max_length=10)),
                ('income_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('religion', models.CharField(choices=[('hindu', 'Hindu'), ('muslim', 'Muslim'), ('christian', 'Christian'), ('other', 'Other')], max_length=20)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('personality_traits', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='AggregateEmotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.JSONField(default=dict)),
                ('news_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.newsitem')),
            ],
        ),
        migrations.CreateModel(
            name='EmotionalResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(choices=[('joy', 'Joy'), ('sadness', 'Sadness'), ('anger', 'Anger'), ('fear', 'Fear'), ('disgust', 'Disgust'), ('surprise', 'Surprise'), ('optimism', 'Optimism'), ('anxiety', 'Anxiety'), ('compassion', 'Compassion'), ('outrage', 'Outrage')], max_length=20)),
                ('intensity', models.FloatField()),
                ('explanation', models.TextField(blank=True, null=True)),
                ('news_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.newsitem')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.persona')),
            ],
        ),
    ]
