# Generated by Django 5.1.3 on 2024-11-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
