# Generated by Django 5.1.3 on 2024-11-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_persona_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='religion',
            field=models.CharField(max_length=20),
        ),
    ]
