# Generated by Django 5.1.3 on 2024-12-03 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0006_aggregateemotion_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactAssessmentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('news_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.newsitem')),
            ],
        ),
    ]
