# Generated by Django 5.1.3 on 2024-12-03 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0007_impactassessmenttask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImpactAssessmentTask',
        ),
    ]
