# Generated by Django 5.1.3 on 2024-12-05 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0009_aggregateemotion_demographic_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aggregateemotion',
            name='demographic_summary',
        ),
    ]
