# Generated by Django 5.1.3 on 2024-12-10 05:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0011_aggregateemotion_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemographicCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('project_reference', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='persona',
            name='age_group',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='income_level',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='religion',
        ),
        migrations.AddField(
            model_name='persona',
            name='demographic_categories',
            field=models.ManyToManyField(blank=True, to='simulator.demographiccategory'),
        ),
        migrations.CreateModel(
            name='DemographicSubcategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='simulator.demographiccategory')),
            ],
        ),
    ]
