# Generated by Django 5.1.3 on 2024-12-10 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0012_demographiccategory_remove_persona_age_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='demographic_categories',
        ),
    ]
