# Generated by Django 5.1.3 on 2024-12-10 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0015_alter_category_description_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('category', 'name', 'percentage')},
        ),
    ]
