# Generated by Django 5.1.3 on 2024-12-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0016_alter_subcategory_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
