# Generated by Django 5.1.3 on 2024-12-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0020_alter_persona_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
