# Generated by Django 5.1.3 on 2024-12-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0021_alter_persona_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='personality_traits',
        ),
        migrations.AddField(
            model_name='persona',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
