# Generated by Django 5.1.3 on 2024-12-16 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0022_remove_persona_personality_traits_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='description',
            new_name='personality_description',
        ),
    ]
