# Generated by Django 5.1.3 on 2024-12-18 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0024_personagenerationtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='PossibleUserResponses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='possible_responses', to='simulator.newsitem')),
            ],
        ),
    ]
