# Generated by Django 5.1.3 on 2024-12-18 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0025_possibleuserresponses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emotionalresponse',
            name='emotion',
        ),
        migrations.AddField(
            model_name='emotionalresponse',
            name='user_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='simulator.possibleuserresponses'),
        ),
    ]
