# Generated by Django 5.1.3 on 2024-12-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0026_remove_emotionalresponse_emotion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMModelAndKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('active', models.BooleanField(choices=[(True, 'True'), (False, 'False')], default=False)),
                ('provider_name', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google Generative AI')], max_length=50)),
            ],
        ),
    ]
