# Generated by Django 5.1.3 on 2024-12-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0028_promptmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptmodel',
            name='task_name',
            field=models.CharField(choices=[('personality_description', 'Personality Description'), ('generate_user_response', 'Generate User Response')], default='personality_description', max_length=50, unique=True),
        ),
    ]
