# Generated by Django 5.1.3 on 2024-12-23 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0030_remove_personagenerationtask_population_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawPersonaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_data', models.JSONField()),
                ('city', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_data', to='simulator.persona')),
            ],
        ),
    ]
