# Generated by Django 4.2.17 on 2025-01-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0032_alter_category_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagenerationtask',
            name='population',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
